config/routes.rb
Rails.application.routes.draw do

  resources :movies, except: [:new, :edit, :update] do
    collection do
      resources :reviews, except: [:index, :show] do
        collection do
          get "search", to: "reviews#search", as: :reviews_search
        end
      end
    end
  end

  devise_for :users, controllers: {
                       passwords: "users/passwords",
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                     }

  devise_scope :user do
    root to: "pages#home"
    get "/account", to: "pages#account", as: :account
    get "/email_sent", to: "users/passwords#email_sent", as: :email_sent
    get "/user/edit_account", to: "users/registrations#edit_account", as: :edit_account
    get "/user/edit_password", to: "users/registrations#edit", as: :edit_password
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie, only: %i[show edit update destroy]

  # GET /movies or /movies.json
  def index
    get_available_genres
    get_available_years
    get_available_ratings

    # If the user gives a completely empty search
    if params.present? && params[:searched_terms] == "" && params[:searched_scores] == "0" && params.to_unsafe_h.count == 5
      @movies = Movie.includes(:review).all.order(title: :asc)
    # filtering the movies based on the search
    elsif params && params[:commit]&.[]("Search").present?
      searched_years = params[:searched_years].map(&:to_i) if params[:searched_years].present?      
      filtered_search = FilterSearch.new(params[:searched_terms], params[:searched_genres], searched_years, params[:searched_ratings], params[:searched_scores])
      @movies = filtered_search.execute_search
    # When no search is present
    else
      @movies = Movie.includes(:review).all.order(title: :asc)
    end
  end

  # GET /movies/1 or /movies/1.json
  def show
    @review = @movie.review
    if @movie.nil?
      redirect_to movies_url
    end
  end


  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)
    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    if @movie.destroy
      redirect_to movies_url, notice: "Movie was successfully destroyed."
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def filter_attribute_value(value)
    Array(value).reject(&:empty?)
  end

  # Only allow a list of trusted parameters through
  def movie_params
    params.permit(:searched_terms, searched_genres: [], searched_years: [], searched_ratings: [], searched_scores: [])
  end

  # set movie
  def set_movie
    @movie = Movie.find(params[:id])
  end

  # for finding genres
  def get_available_genres
    @avaliable_genres = Genre.pluck(:name).sort
  end

  # for finding & formatting years
  def get_available_years
    @movie_years = Movie.pluck(:start_year).uniq.sort
  end

  # for finding ratings
  def get_available_ratings
    @available_ratings = [
      "G", "PG", "PG-13", "R",
      "NC-17", "TV-Y", "TV-Y7",
      "TV-G", "TV-PG", "TV-14", "TV-MA",
      "N/A",
    ]
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def structure_movie_genres(movie)
    unformatted_movie_genres = ""
    movie.genres.each do |genre|
      unformatted_movie_genres << genre.name
    end
    formatted_movie_genres = unformatted_movie_genres.gsub(/(?<=\p{Lu})(?=\p{Lu}\p{Ll})|(?<=\p{Ll})(?=\p{Lu})/, ", ")
    formatted_movie_genres
  end


  private
  
  # temporary table will be renamed and used as primary but for now so I dont lose data it is named temporary
  def save_start_years_to_temp_start_year_column
    movies = Movie.all
    int_years = movies.map do |m|
      start_year_as_integer = m.year[0..3].to_i
      m.update(temp_start_year: start_year_as_integer)
      start_year_as_integer
    end
    puts int_years
  end
  def save_end_year_to_end_year_column
    movies = Movie.all
    int_years = movies.map do |m|
      if m.year.length == 9
        end_year_as_integer = m.year[5..8].to_i
        m.update(end_year: end_year_as_integer)
      end
    end
  end
end

app/views/movies/_form.html.erb
<%= form_with(model: movie, class: "contents") do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>
      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :title %>
    <p><%= @movie.title %>
    </div>
    <div class="my-5">
      <%= form.label :review %>
      <%= form.text_area :review, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= form.label :year %>
      <%= form.text_field :year, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= form.label :genre %>
      <%= form.text_field :genre, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= form.label :rating %>
      <%= form.text_field :rating, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= form.label :score %>
      <%= form.text_field :score, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="inline">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>

app/views/movies/index.html.erb
<body class="">
  <header class="flex justify-center">
    <!-- Desktop Form ______________________________________________________________________________-->
    <%= form_with(model: @movie, method: :get, id: "large-search-form", class: "hidden lg:flex mt-5 w-3/5") do |sel| %>
      <div data-controller="clearform" class="w-full">
        <div class="flex items-center justify-center">
          <!-- Text Search -->
          <div class="flex flex-row justify-between w-full h-10">
            <%= sel.text_field :searched_terms, placeholder: "Search movies", class: "w-full rounded-md" %>
            <%= sel.submit "Search", class: "flex ml-4 justify-center items-center text-center hover:cursor-pointer border-2 border-blue-500 rounded w-48 bg-blue-50 h-10 whitespace-nowrap hover:bg-blue-100" %>
            <%= link_to "Reset search", "#", class: "flex ml-4 justify-center p-4 items-center text-center hover:cursor-pointer border-2 border-blue-500 rounded w-48 bg-blue-50 h-10 whitespace-nowrap hover:bg-blue-100", "data-action" => "click->clearform#clearForm" %>
            <% if current_user.present? && current_user.admin? %>
              <%= link_to "New Review", reviews_search_reviews_path, class: "flex ml-4 p-4 justify-center items-center text-center hover:cursor-pointer border-2 border-green-500 rounded w-48 bg-green-50 h-10 whitespace-nowrap hover:bg-green-100", id: "new_review" %>
            <% end %>
          </div>
        </div>
        <!-- Drop Downs for lg screen -->
        <div data-controller="filter-dropdown" class="flex justify-between mt-4">
          <!-- genre selection -->
          <div class="w-52">
            <!-- the button -->
            <button id="genre-button" data-action="click->filter-dropdown#toggleGenre" type="button" class="w-full pt-2.5 border-2 border-b-0 text-start pr-2 lg:pr-4 h-8 flex items-center justify-between rounded">              
              <span class="lg:ml-5 ml-2">Genre</span>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="flex lg:w-6 lg:h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
              </svg>
            </button>
            <!-- the menu -->
            <div id="genre-dropdown" class="max-h-32 pt-3 flex flex-col overflow-y-auto border-2 border-t-0">
              <div data-filter-dropdown-target="genreContent">
                <% @avaliable_genres.each do |genre| %>
                  <div class="pl-2 pr-10 flex items-center mb-1 hover:bg-slate-100">
                    <%= sel.check_box :searched_genres, { multiple: true, include_hidden: false }, genre %>
                    <span class="px-1"><%= genre %></span>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <!-- year selection -->
          <div class="w-52">
            <!-- the button -->
            <button data-action="click->filter-dropdown#toggleYear" type="button" class="w-full pt-2.5 border-2 border-b-0 text-start pr-2 lg:pr-4 h-8 flex items-center justify-between rounded">              
              <span class="lg:ml-5 ml-2">Year</span>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="flex lg:w-6 lg:h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
              </svg>
            </button>
            <!-- the menu -->
            <div class="max-h-32 max-w-40 pt-3 flex flex-col overflow-y-auto border-2 border-t-0">
              <div data-filter-dropdown-target="yearContent">
                <% @movie_years.each do |year| %>
                  <div class="pl-2 py-0.5 hover:bg-slate-100">
                    <%= sel.check_box :searched_years, { multiple: true, include_hidden: false }, year %>
                    <span class=""><%= year %></span>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <!-- Rating Selection -->
          <div class="w-52">
            <!-- the button -->
            <button data-action="click->filter-dropdown#toggleRating" type="button" class="w-full pt-2.5 border-2 border-b-0 text-start pr-2 lg:pr-4 h-8 flex items-center justify-between rounded">              
              <span class="lg:ml-5 ml-2">Rating</span>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="flex lg:w-6 lg:h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
              </svg>
            </button>
            <!-- the menu -->
            <div class="max-h-32 max-w-40 pt-3 flex flex-col overflow-y-auto border-2 border-t-0">
              <div data-filter-dropdown-target="ratingContent">
                <% @available_ratings.each do |rating| %>
                  <div class="pl-2 py-0.5 hover:bg-slate-100">
                    <%= sel.check_box :searched_ratings, { multiple: true, include_hidden: false }, rating %>
                    <span class=""><%= rating %></span>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <!-- Score Selection -->
          <div class="w-52"> <!-- Increase the width to your desired size, e.g., w-64 or w-72 -->
            <!-- the button -->
            <button data-action="click->filter-dropdown#toggleScore" type="button" class="w-full pt-2.5 border-2 border-b-0 text-start pr-2 lg:pr-4 h-8 flex items-center justify-between rounded">              
              <span class="lg:ml-5 ml-2">Score</span>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="flex lg:w-6 lg:h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
              </svg>
            </button>
            <!-- the menu -->
            <div class="max-h-32 max-w-62 pt-3 flex flex-col border-2 border-t-0">
              <div data-filter-dropdown-target="scoreContent" class="flex justify-center items-center m-4 h-32">
                <%= sel.range_field :searched_scores, id: "slider", in: 0..10, value: 0, class: "w-48 mb-8" %> <!-- Increase the width, e.g., w-56 or w-64 -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <!-- Mobile form -->
  <div class="lg:hidden w-11/12">
    <%= form_with(model: @movie, method: :get, id: "small-search-form", class: " mt-4 w-full ") do |sel| %>
      <div class="flex" data-controller="clearform">
        <h1 class="font-bold mt-3.5">Movie Reviews</h1>
        <div class="flex flex-row justify-end ml-auto">
        <%= link_to "Reset search", "#", class: "mt-2.5 flex text-center justify-center ml-auto items-center ml-auto border-2 border-blue-500 rounded text-center w-32 bg-blue-50 h-8 whitespace-nowrap hover:cursor-pointer hover:bg-blue-100" , "data-action" => "click->clearform#clearForm" %>
        <% if current_user.present? && current_user.admin? %>
          <%= link_to "New Review", reviews_search_reviews_path, class: "mt-2.5 ml-4 flex text-center justify-center items-center border-2 border-green-500 rounded text-center w-32 bg-green-50 h-8 whitespace-nowrap hover:bg-green-100" %>
        <% end %>
        </div>
      </div>
      <div class="mt-4">
        <div class="flex items-center justify-center">
          <!-- Text Search -->
          <div class="flex flex-col w-full h-10">
            <%= sel.text_field :searched_terms, placeholder: "Search movies", class: " rounded-md" %>
            <%= sel.submit "Search", class: "hidden" %>
          </div>
        </div>
        <!-- Drop Downs for sm screen -->
        <div data-controller="filter-dropdown" class=" mt-4">
          <!-- Selection Buttons -->
          <div class="h-1/2 w-full flex flex-row justify-between mb-1">
            <!-- genre selection button -->
            <button data-action="click->filter-dropdown#toggleGenre" type="button" class="border-2 border-blue-400 bg-blue-50 w-20 h-8 rounded hover:bg-blue-100">              
              <span class="text-center">Genre</span>
            </button>
            <!-- year selection button -->
            <button data-action="click->filter-dropdown#toggleYear" type="button" class="border-2 border-blue-400 bg-blue-50 w-20 h-8 rounded hover:bg-blue-100">              
              <span class="text-center">Year</span>
            </button>
            <!-- Rating Selection button -->
            <button data-action="click->filter-dropdown#toggleRating" type="button" class="border-2 border-blue-400 bg-blue-50 w-20 h-8 rounded hover:bg-blue-100">              
              <span class="text-center">Rating</span>
            </button>
            <!-- Score Selection button -->
            <button data-action="click->filter-dropdown#toggleScore" type="button" class="border-2 border-blue-400 bg-blue-50 w-20 h-8 rounded hover:bg-blue-100">              
              <span class="text-center">Score</span>
            </button>
          </div>
          <!-- Selection Menus -->
          <div class="w-full flex flex-col">
            <!-- the genre menu -->
            <div data-filter-dropdown-target="genreContent">
              <div class="max-h-32 flex-col overflow-y-auto border-4 rounded">
                <% @avaliable_genres.each do |genre| %>
                  <div class="pl-2 hover:bg-slate-100">
                    <%= sel.check_box :searched_genres, { multiple: true, include_hidden: false }, genre %>
                    <span class=""><%= genre %></span>
                  </div>
                <% end %>
              </div>
            </div>
            <!-- the year menu -->
            <div data-filter-dropdown-target="yearContent">
              <div class="max-h-32 flex-col overflow-y-auto border-4 rounded">
                <% @movie_years.each do |year| %>
                  <div class="pl-2 hover:bg-slate-100">
                    <%= sel.check_box :searched_years, { multiple: true, include_hidden: false }, year %>
                    <span class=""><%= year %></span>
                  </div>
                <% end %>
              </div>
            </div>
            <!-- the rating menu -->
            <div data-filter-dropdown-target="ratingContent" class="">
              <div class="max-h-32 flex-col overflow-y-auto border-4 rounded">
                <% @available_ratings.each do |rating| %>
                  <div class="pl-2 hover:bg-slate-100">
                    <%= sel.check_box :searched_ratings, { multiple: true, include_hidden: false }, rating %>
                    <span class=""><%= rating %></span>
                  </div>
                <% end %>
              </div>
            </div>
            <!-- the score menu -->
            <div data-filter-dropdown-target="scoreContent" class="flex justify-center items-center h-32 border-4 rounded">
              <div class="max-h-32 flex-col">
                <%= sel.range_field :searched_scores, id: "slider", in: 0..10, value: 0, class: "lg:w-48 w-80 mb-8" %> <!-- Increase the width, e.g., w-56 or w-64 -->
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </header>
  <main class="flex flex-row flex-wrap mb-20">
    <% if @movies.present? %>
      <% @movies.each do |movie| %>
        <div class="flex flex-col items-center w-1/2 lg:w-1/4 mt-10 ">
          <div class="flex-row w-3/5 h-2/5 lg:w-3/4 lg:h-5/6 mb-2 mt-10 mr-10 ml-10 rounded flex-grow">
            <%= link_to movie_path(movie), class: "styling-none" do %>
              <div class="aspect-w-3 aspect-h-4">
                <img src="<%= movie.poster %>" alt="Movie Poster" class="object-cover hover:object-contain object-center w-full h-full">
              </div>
            <% end %>
          </div>
          <div class="flex flex-col mt-2 items-center w-3/4 bottom-0">
            <h2 class="text-center w-4/5"><%= movie.title %></h2>
            <p><%= movie.review.score if movie.present? %>/10</p>
            <% if current_user.admin? %>
              <div class="flex flex-col justify-between items-center lg:flex-row mt-1 lg:mt-4 w-full">
                <%= link_to "Edit", movie_path(movie), class: "flex justify-center items-center border-2 border-green-300 w-28 h-7 lg:h-9 mt-2 lg:m-0 text-green-600 bg-green-50 hover:bg-green-100 rounded" %>
                <%= link_to "Delete", movie_path(movie), data: { turbo_frame: "delete_modal" }, class: "text-center border-2 border-red-300 text-red-600 bg-red-50 hover:bg-red-100 w-28 h-7 mt-2 lg:h-9 lg:mt-0 lg:m-0 flex items-center justify-center rounded" %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="flex justify-center items-center text-center mt-60 mx-auto">
        <h1 class="text-5xl text-red-400">No movies match your search criteria</h1>
      </div>
    <% end %>
  </main>



</body>

app/views/movies/show.html.erb
<!DOCTYPE html>
<html>
  <body>
    <main class="flex flex-col p-2">
      <div class="">
        <div class="flex flex-wrap mt-5 lg:flex justify-center lg:flex-nowrap lg:w-3/4 rounded container mx-auto p-2 border-4 border-double border-gray-300">
          <% if @movie.present? %>
            <h1 class="lg:hidden mt-2 flex flex-row w-full justify-center text-xl font-bold mb-4">
              <%= @movie.title %>
            </h1>
            <img src="<%= @movie.poster %>" alt="Movie Poster" class="lg:mr-5 mb-4 lg:mb-0">
            <div class="flex flex-wrap justify-center lg:flex-nowrap lg:flex-col overflow-y-scroll overflow-x-hidden">
              <div class="w-full mb-4 text-center ">
                <h1 class="hidden lg:flex lg:text-3xl font-bold">
                  <%= @movie.title %>
                </h1>
                <p class="text-slate-700 lg:mt-6 lg:flex lg:justify-start font-bold">
                  <%= @movie.start_year %>
                  <% if @movie.end_year.present?%>
                    - <%= @movie.end_year%>
                  <% end %>
                  | <%= @movie.runtime %> | <%= @movie.rating %> | <%= structure_movie_genres(@movie) %>
                </p>
              </div>
              <div class="w-full mt-2 lg:mt-4 lg:mr-60 lg:w-1/2">
                <h4 class="font-bold">Director</h4>
                <p><%= @movie.director %></p>
              </div>
              <div class="w-full mt-2 lg:mt-4 lg:mr-60 lg:w-1/2">
                <h4 class="font-bold">Actors</h4>
                <p><%= @movie.actors %></p>
              </div>
              <div class="w-full mt-2 lg:mt-4 lg:mr-60 lg:w-1/2">
                <h4 class="font-bold">Awards</h4>
                <p><%= @movie.awards %></p>
              </div>
              <div class="w-full mt-2 max-h-14 lg:mt-4 lg:mr-60 lg:w-full">
                <h4 class="font-bold sticky top-0 w-full bg-white">Summary</h4>
                <div class="">
                  <p><%= @movie.plot %></p>
                </div>
              </div>
            </div>
          <% else %>
            <p>No movie found.</p>
          <% end %>
        </div>
      </div>
      <turbo-frame id="edit_review_form" class="my-8 w-full">
        <div class="mx-auto lg:w-3/4">
          <% if current_user.admin? %>
            <div class="flex justify-between w-full rounded border-4 border-double mb-8 border-gray-300 bg-gray-100 h-20">
              <label class="text-left text-xl my-auto ml-2">Reviewer Options</label>
              <div class="flex my-auto">
                <%= link_to "Edit", edit_review_path(@movie.review.id), class: "text-center border-2 bg-green-50 border-green-500 text-green-700 hover:bg-green-100 rounded py-1 px-4 m-2 h-9 w-20 " %>
                <%= link_to "Delete", movie_path(@movie), data: { turbo_frame: "delete_modal" }, class: "text-center border-2 bg-red-50 border-red-500 text-red-700 hover:bg-red-100 rounded py-1 px-4 m-2 h-9 w-20" %>
              </div>
            </div>
          <% end %>
          <div class="lg:mx-auto lg:py-4" id="edit_review_div">
            <label class="text-xl px-2 font-bold">Critic Review</label>
            <p class="my-4 p-2"><%= @movie.review.content %></p>
          </div>
          <div class="flex flex-row text-align-center rounded lg:p-4 border-4 border-double border-gray-300 bg-gray-100 h-20">
            <h1 class="text-4xl mr-auto my-auto">Critic Score</h1>
            <p class="w-1/4 text-3xl text-right my-auto"><%= @movie.review.score %>/10</p>
          </div>
        </div>
      </div>
    </turbo-frame>
  </main>
  <div class="hidden">
    <%= render "devise/shared/delete" %>
  </div>
</body>
</html>