config/routes.rb
Rails.application.routes.draw do

  resources :movies, except: [:new, :edit, :update] do
    collection do
      resources :reviews, except: [:index, :show] do
        collection do
          get "search", to: "reviews#search", as: :reviews_search
        end
      end
    end
  end

  devise_for :users, controllers: {
                       passwords: "users/passwords",
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                     }

  devise_scope :user do
    root to: "pages#home"
    get "/account", to: "pages#account", as: :account
    get "/email_sent", to: "users/passwords#email_sent", as: :email_sent
    get "/user/edit_account", to: "users/registrations#edit_account", as: :edit_account
    get "/user/edit_password", to: "users/registrations#edit", as: :edit_password
  end
  
end

app/views/pages/account.html.erb
<html>
  <body>
    <main class="flex w-screen h-screen flex-col">
      <div class="mt-10 lg:mt-40">
        <div class="flex justify-center w-full text-xl lg:text-3xl font-bold mb-10 lg:mb-0">
          <h1>Account Information</h1>
        </div>
        <div class="flex justify-between p-6 flex-row lg:text-xl lg:py-4 lg:px-8">
          <p class="lg:font-bold lg:ml-60">Name</p>
          <p class="lg:font-bold lg:mr-60"><%= current_user.first_name %> <%= current_user.last_name %></p>
        </div>
        <div class="flex justify-between p-6 flex-row lg:text-xl lg:py-4 lg:px-8">
          <p class="lg:font-bold lg:ml-60">Username</p>
          <p class="lg:font-bold lg:mr-60"><%= current_user.username %></p>
        </div>
        <div class="flex justify-between p-6 flex-row lg:text-xl lg:py-4 lg:px-8">
          <p class="lg:font-bold lg:ml-60">Email</p>
          <p class="lg:font-bold lg:mr-60"><%= current_user.email %></p>
        </div>
        <div class="flex flex-col lg:flex-row justify-center items-center mt-8">
          <%= link_to "Edit Profile", edit_account_path, class: "flex justify-center items-center h-8 w-36 lg:h-10 lg:w-40 border-2 bg-blue-50 text-blue-700 hover:bg-blue-100 border-blue-600 lg:mr-20 mb-10 lg:mb-0 rounded" %>
          <%= link_to "Password Reset", edit_password_path, class: "flex justify-center items-center h-8 w-36 lg:h-10 lg:w-40 border-2 bg-blue-50 text-blue-700 hover:bg-blue-100 border-blue-600 lg:ml-10 rounded" %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<div class="flex items-center justify-center flex-col mt-5">
  <div class="mb-10 lg:mb-0 flex justify-center">
    <p class="text-black text-3xl font-bold lg:text-7xl lg:mt-16 lg:mb-12">The Movie Critic</p>
  </div>
  <div class="px-3">
    <div class="border-2 p-2">
      <h2 class="text-xl font-bold text-center mb-6">Sign in</h2>
      <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div class="flex flex-col justify-center">
          <%= f.label :email, class: "m-2 ml-9 text-gray-700 text-sm font-semibold", id: "email-inp"%>
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "mx-auto w-3/4 border border-gray-300 rounded-md py-2 px-3 focus:outline-none focus:ring-2 focus:ring-indigo-500" %>
        </div>
        <div class="flex flex-col justify-center">
          <%= f.label :password, class: "m-2 ml-9 text-gray-700 text-sm font-semibold" %>
          <%= f.password_field :password, autocomplete: "current-password", class: "mx-auto w-3/4 border border-gray-300 rounded-md py-2 px-3 focus:outline-none focus:ring-2 focus:ring-indigo-500" %>
        </div>
        <div class="flex items-center justify-center">
          <div class="flex justify-center items-center w-">
            <%= f.submit "Submit", data: { turbo_frame: "_top", action: "redirect_to tasks_url" }, class: "mt-4 mb-2 w-52 items-center bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="mt-4 text-sm text-center">
      <%= link_to "Forgot Password?", new_password_path(resource), class: "text-purple-400 font-bold" %>
    </div>
    <div class=" mt-10 lg:mt-16 mx-auto w-60 h-40 flex flex-col justify-center items-center bg-slate-100 mb-10">
      <p class="flex items-center justify-center text-black px-4 ml-auto text-2xl text-center">Create an Account Today!</p>
      <%= link_to "Sign Up", new_user_registration_path, class: "w-52 mt-4 mx-auto px-4 py-2 rounded-md bg-blue-500 text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 flex items-center justify-center", id: "signup" %>
    </div>
  </div>