config/routes.rb
Rails.application.routes.draw do

  resources :movies, except: [:new, :edit, :update] do
    collection do
      resources :reviews, except: [:index, :show] do
        collection do
          get "search", to: "reviews#search", as: :reviews_search
        end
      end
    end
  end

  devise_for :users, controllers: {
                       passwords: "users/passwords",
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                     }

  devise_scope :user do
    root to: "pages#home"
    get "/account", to: "pages#account", as: :account
    get "/email_sent", to: "users/passwords#email_sent", as: :email_sent
    get "/user/edit_account", to: "users/registrations#edit_account", as: :edit_account
    get "/user/edit_password", to: "users/registrations#edit", as: :edit_password
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  require "net/http" # for api requests
  before_action :set_review, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def search
    @review = Review.new
    authorize @review
    if params.present? && params[:review].present? && params[:review][:title].present?
      title = params[:review][:title]
      retrieve_movie_list(title)
      @search_performed = !title.nil?
      @exsisting_movies_with_api_movie_id = Review.joins(:movie).select("reviews.api_movie_id, reviews.movie_id")
    end
  end

  # GET /reviews/new
  def new
    @review = Review.new
    authorize @review
    @movie_data = retrieve_selected_movie_details(params[:api_movie_id])
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new
    authorize @review
    ActiveRecord::Base.transaction do
      if params[:review][:api_movie_id].present?
        movie_data_hash = retrieve_selected_movie_details(params[:review][:api_movie_id])
        # create genre
        genres = GenreCreator.create_genre(movie_data_hash)
        # create movie
        movie = MovieCreator.create_movie(movie_data_hash, genres)
      else
        notice "The movie you selected or the necessary details do not exist. Please try again."
      end

      @review = Review.new(review_params)
      @review.movie_id = movie.id

      respond_to do |format|
        if @review.save
          format.html { redirect_to movie_path(@review.movie), notice: "Review was successfully created." }
        else
          format.turbo_stream {
            render turbo_stream: turbo_stream.replace(
              "error_messages",
              partial: "devise/shared/error_messages",
            )
          }
        end
      end
      raise ActiveRecord::Rollback if @review.id.nil?
    end
  end

  # GET /reviews/1/edit
  def edit
    @movie = @review.movie
    @review = Review.find(params[:id])
    authorize @review
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    @movie = @review.movie
    if @review.update(review_params)
      redirect_to @movie
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def review_params
    params.require(:review).permit(:content, :score, :api_movie_id)
  end

  def retrieve_movies(title)
    @api_key = "6b86fd48"
    api_request = URI("http://www.omdbapi.com/?apikey=#{@api_key}&s=#{CGI.escape(title)}")
    response = Net::HTTP.get(api_request)
    JSON.parse(response)
  end

  def retrieve_movie_list(title)
    @movies = self.retrieve_movies(title)
  end

  def retrieve_selected_movie_details(api_movie_id)
    @api_key = "6b86fd48"
    api_request = URI("http://www.omdbapi.com/?apikey=#{@api_key}&i=#{CGI.escape(api_movie_id)}") if api_movie_id.present?
    response = Net::HTTP.get(api_request)
    JSON.parse(response)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: @review, class: "w-full") do |form| %>
  <%= form.hidden_field :api_movie_id, value: @movie_data["imdbID"] %>
  <% if @review.errors.any? %>
    <div>
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :review %>
    <%= form.text_area :content, rows: 10, class: "block shadow rounded-md border-4 border-double border-slate-300 outline-none px-3 py-2 mt-2 mr-1 w-full" %>
  </div>
  <div class="">
    <%= form.label :score %>
    <%= form.text_field :score, class: "block shadow rounded-md border-4 border-double border-slate-300 outline-none px-3 py-2 mt-2" %>
  </div>
  <div class="actions mt-4 flex">
    <%= form.submit value: "Save", class: "bg-green-50 hover:bg-green-100 border-2 border-green-600 py-2 px-4 rounded mr-2 w-24" %>
    <%= link_to "Cancel", reviews_search_reviews_path, class: "text-center bg-red-50 hover:bg-red-100 border-2 border-red-600 py-2 px-4 w-24 rounded" %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<%= turbo_frame_tag :edit_review_form do %>
  <%= form_with(model: @review, class: "w-full") do |form| %>
    <%= form.hidden_field :api_movie_id, value: @movie.review.api_movie_id if @movie.review.api_movie_id %>
    <% if @review.errors.any? %>
      <div>
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
        <ul>
          <% @review.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="my-5 ">
      <%= form.label :review %>
      <%= form.text_area :content, rows: 10, class: "block shadow rounded-md border-4 border-slate-300 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="">
      <%= form.label :score %>
      <%= form.text_field :score, class: "block shadow rounded-md border-4 border-slate-300 outline-none px-3 py-2 mt-2 w-1/" %>
    </div>
    <div class="actions mt-4 flex">
      <%= form.submit value: "Save", class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mr-2" %>
      <%= link_to "Cancel", movie_path(@movie), class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
  <% end %>
<% end %>

app/views/reviews/new.html.erb
<!DOCTYPE html>
<html>
  <body>
    <main class="flex flex-col lg:flex-wrap lg:mt-10">
      <div class="flex flex-wrap mt-5 justify-center lg:flex-nowrap md:w-3/4 mx-auto lg:mx-auto md:border-4 rounded border-double lg:m-2 p-2">
        <% if @movie_data.present? %>
          <h1 class="lg:hidden flex flex-row w-full justify-center mb-4 text-xl font-bold"><%= @movie_data["Title"] %></h1>
          <img src="<%= @movie_data["Poster"] %>" alt="Movie Poster" class="lg:mr-5  border-2 max-h-4/5 my-auto">
          <div class="flex flex-wrap justify-center  lg:flex-nowrap lg:flex-col lg:mt-2 lg:mb-4">
            <div class="w-full lg:w-full overflow-y-scroll">
              <div class="w-full text-center mt-2 lg:text-left lg:mr-60 lg:mt-1 lg:w-full ">
                <h1 class="hidden lg:flex lg:text-3xl"><%= @movie_data["Title"] %></h1>
                <p class="text-slate-700 lg:mt-1"><%= @movie_data["Year"] %> | <%= @movie_data["Runtime"] %> | <%= @movie_data["Rated"] %> | <%= @movie_data["Genre"] %></p>
              </div>
              <div class="w-full mt-1 lg:mt-4 lg:mr-60 lg:w-1/2">
                <h4 class="font-bold">Director</h4>
                <p><%= @movie_data["Director"] %></p>
              </div>
              <div class="w-full mt-1 lg:mt-4 lg:mr-60 lg:w-1/2">
                <h4 class="font-bold">Actors</h4>
                <p><%= @movie_data["Actors"] %></p>
              </div>
              <div class="w-full mt-1 lg:mt-4 lg:mr-60 lg:w-1/2">
                <h4 class="font-bold">Awards</h4>
                <p><%= @movie_data["Awards"] %></p>
              </div>
              <div class="w-full mt-1 overflow-y-auto max-h-40 lg:mt-4 lg:mr-60">
                <h4 class="font-bold sticky top-0 w-3/4 text-left bg-none">Summary</h4>
                <div>
                  <p><%= @movie_data["Plot"] %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <%= turbo_frame_tag "error_messages" do %>
          <% end %>
          <div class="w-full md:w-3/4 mx-auto flex flex-wrap justify-center p-2 lg:p-0 lg:mx-auto mb-10 lg:mb-10 lg:mt-4 lg:w-3/4">
            <%= render partial: "form" %>
          </div>
        </div>
      <% else %>
        <p>No movie found.</p>
      <% end %>
    </main>
  </body>
</html>

app/views/reviews/search.html.erb
<h1 class="flex justify-center font-bold m-4">
  What movie would you like to review?
</h1>
<div>
  <%= form_with(model: @review, url: reviews_search_reviews_path, method: :get, class: "w-full") do |sel| %>
    <div class="flex items-center justify-center m-2" data-controller="clearform">
      <%= sel.text_field :title, value: params.dig(:movie, :title), placeholder: "Search movies", class: "w-1/2 p-2 rounded-md" %>
      <%= sel.submit "Search", class: "bg-blue-50 border-2 border-blue-700 hover:bg-blue-100 rounded-md w-24 p-2 ml-2 hover:cursor-pointer" %>
      <%= link_to "Reset", "#", class: "bg-blue-50 border-2 border-blue-700 hover:bg-blue-100 rounded-md w-24 py-2 px-4 ml-2 text-center", "data-action" => "click->clearform#clearForm" %>
    </div>
  <% end %>
</div>
<div class="flex flex-wrap flex-row">
  <% if @movies && @movies["Search"].present? %>
    <h2 class="flex w-full justify-center mt-4">Search Results:</h2>
    <% if @movies.present? && @movies["Search"].present? %>
      <% @movies["Search"].each_with_index do |movie, index| %>
        <div class="flex flex-col items-center w-1/2 lg:w-1/4" id="search-results-<%= index + 1 %>">
          <div class="w-3/5 h-2/5 lg:w-3/5 lg:h-3/5 mb-2 mt-10 mr-10 ml-10 rounded overflow-hidden flex-grow">
            <div class="aspect-w-3 aspect-h-4">
              <img src="<%= movie["Poster"] %>" alt="Movie Poster" class="object-cover object-center w-full h-full">
            </div>
          </div>
          <div class="flex flex-col items-center w-full p-4 bottom-0">
            <h2 class="text-center mb-4 w-4/5"><%= movie["Title"] %></h2>
            <div class="flex justify-center align-baseline">
              <% if @exsisting_movies_with_api_movie_id.map(&:api_movie_id).include?(movie["imdbID"]) %>
                <% # Movie has a review associated, display "Edit" and "Delete" buttons %>
                <% review = @exsisting_movies_with_api_movie_id.find { |r| r.api_movie_id == movie["imdbID"] } %>
                <%= link_to "Edit", movie_path(review.movie_id), class: "flex justify-center items-center rounded-md h-10 w-20 py-1 px-4 m-2 w-20 border-2 border-green-700 bg-green-50 hover:bg-green-100 text-green-700",  id: "edit-button-#{index + 1}" %>
                <%= link_to "Delete", movie_path(review.movie_id), data: { turbo_frame: "delete_modal" }, class: "flex justify-center items-center text-center rounded-md py-1 px-4 m-2 w-20 border-2 border-red-700 bg-red-50 hover:bg-red-100 text-red-700" %>
              <% else %>
                <% # Movie doesn't have a review associated, display "Review" button %>
                <%= link_to "Review", new_review_path(api_movie_id: movie["imdbID"]), class: "rounded-md flex justify-center items-center text-center h-10 w-24 p-2 lg:py-1 lg:px-4 m-2 border-2 border-green-700 bg-green-50 hover:bg-green-100 text-green-700" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% elsif @search_performed && @movies.nil? %>
    <div class="flex h-3/4 w-screen items-center justify-center">
      <div class="flex justify-center items-center w-1/2 h-16 rounded">
        <h1 class=" text-center text-3xl">No Movies Found</h1>
      </div>
    </div>
  <% else %>
  <% end %>
</div>